name: push into my repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Create freshtrash directory and move output
        run: |
          mkdir -p freshtrash
          mv output/* freshtrash/
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          source-directory: 'freshtrash'
          destination-github-username: 'sgoldenbird'
          destination-repository-name: 'open-group-Projects'
          user-email: sgoldenbird@gmail.com
          commit-message: 'Deploy Fresh Trash'
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
