name: push into my repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby curl
          sudo gem install mustache
      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Create freshtrash directory and move output contents
        run: |
          mkdir -p fresh-trash
          mv output/* fresh-trash/
          rm -rf output
      - name: Move all remaining project files
        run: |
          shopt -s extglob
          rsync -av --progress ./* fresh-trash/ --exclude fresh-trash --exclude .git --exclude .github
      - name: Verify fresh-trash directory
        run: |
          echo "Contents of fresh-trash directory:"
          ls -la fresh-trash
      - name: Clean up root directory
        run: |
          shopt -s extglob
          rm -rf !(fresh-trash|.git|.github)
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          source-directory: 'fresh-trash'
          destination-github-username: 'sgoldenbird'
          destination-repository-name: 'open-team-deploy'
          user-email: sgoldenbird@gmail.com
          commit-message: 'Deploy Fresh Trash'
          target-branch: main
          target-directory: 'fresh-trash'
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
